name: Runner address discovery

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  amelia:
    runs-on: [self-hosted, device-amelia-m4-16gb]
    timeout-minutes: 5
    steps:
      - run: tailscale ip -4 > address.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: amelia-address
          path: address.txt

  lexie:
    runs-on: [self-hosted, device-lexie-m4-16gb]
    timeout-minutes: 5
    steps:
      - run: tailscale ip -4 > address.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: lexie-address
          path: address.txt
